export enum SceneType {
    ELIPSE_TRACK = "Elipse-Track",
    RECTANGLE_TRACK = "Rectangle-Track",
    CAR = "Car",
    TRACK_BOUNDARY = "Track-Boundary",
    STARTING_GRID = "Starting-Grid",
    ROAD_MARKINGS = "Road-Markings",
    TRACK_GRASS = "Track-Grass",
    LAP_TRACKER = "Lap-Tracker",
    GAME_SCORE = "Game-Score",
    MENU = "Menu",
    COUNTDOWN = "Countdown",
    CONTINUE = "Continue",
    MOUSE_CURSOR = "Mouse-Cursor",
    SOUND_DEMO = "Sound-Demo",
    GAME = "Game",
}
